### ISSUE TITLE
キューを叩くと何故かぬるぽる

### ISSUE THREAD

**Issue by tearaikazuki** [TeamKitten/Calf#5]
キューの中に何か入って用が入って無い用がぬるぽる
```
[JDA MainWS-ReadThread] ERROR JDA - One of the EventListeners had an uncaught exception
java.lang.NullPointerException
	at tk.teamkitten.calf.Main.viewQueue(Main.java:154)
	at tk.teamkitten.calf.Main.onGuildMessageReceived(Main.java:80)
	at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:345)
	at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:64)
	at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:148)
	at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:97)
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:37)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:839)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:738)
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:717)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:877)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

**Comment by TinyKitten** [comment]
誰が実装すべきか明確にするために実装者をアサインしてください。今回はあなたが実装する前提だと思うのでアサインします。

**Comment by TinyKitten** [comment]
原因わかりました。```viewQueue```メソッドでは愚直に```musicManager.player.getPlayingTrack().getInfo();```としていますが、```musicManager.player.getPlayingTrack();```はそもそもNullを返す可能性があります。（トラックを再生していない可能性があるのでこれは当然とも言えますが。）しかしnullアサートをしていないため、null状態の```musicManager.player.getPlayingTrack();```に対してアクセスしており、```NullPointerException```が発生したと思われます。

このIssueは解決とマークし、再発までCloseします。
